node()
{

	stage('gitlab clone')
	{
		checkout scm
	}
	stage('Dump ENV')
	{
		sh('env | sort -n')
		print("Gitlab Trigger Branch: ${BRANCH_NAME}")
	}

    stage('Create Jobs')
    {
         jobDsl targets: ['dsl/jobs/build_root.groovy',
          'dsl/jobs/docker_ansible.groovy',
          'dsl/jobs/docker_terraform.groovy',
          'dsl/jobs/docker_consul.groovy',
          'dsl/jobs/docker_vault.groovy',
          'dsl/jobs/docker_packer.groovy',
          'dsl/jobs/ubi8_hardened.groovy',
          'dsl/jobs/packer_goldenos.groovy'].join('\n'),
         removedJobAction: 'DELETE',
         removedViewAction: 'DELETE',
         lookupStrategy: 'SEED_JOB',
         additionalParameters: [BUILD_BRANCH: "${BRANCH_NAME}"]
    }
}
